import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {
        public let brandButton = Color(.sRGB, red: 240/255, green: 233/255, blue: 233/255, opacity: 1) 
        public let red100 = Color(.sRGB, red: 246/255, green: 16/255, blue: 16/255, opacity: 1) 
        public let color = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
    }
}